### ISSUE TITLE
[Proposal] Method/option to update/add charset meta tag

### ISSUE THREAD

**Issue by blaaat** [thesoftwarefanatics/php-html-parser#11]
When importing and exporting HTML the charset might be changed, but the meta charset tag is not. Resulting in invalid output. I suggest either creating a method which updates/adds an meta charset tag or updating an existing tag automatically on import (with option?)

**Comment by plonknimbuzz** [comment]
did you mean change meta charset in head tag?

can you provide live example?

**Comment by alcaeus** [comment]
Closing due to lack of feedback. @blaaat if you need this functionality, please provide additional information, ideally in the form of a test case to test what you expect to happen.
