### ISSUE TITLE
[REQUEST] Method text return child text

### ISSUE THREAD

**Issue by plonknimbuzz** [thesoftwarefanatics/php-html-parser#13]
I would suggest next update will have this feature.

DOM:
```html
<div class="parent">
   <div class="child1">
       <div class="child2">im here</div>
   </div>
</div>
```
recent:
`$dom->find('.parent')->text` return empty

hopefully will like jquery `text()`
which is like:
`strip_tags($dom->find('.parent')->innerHtml)`

how do you think about this?

**Comment by blacksmoke26** [comment]
@plonknimbuzz  +1

**Comment by plonknimbuzz** [comment]
@blacksmoke26 thanks for your support. i hope @thesoftwarefanatic will read this soon

**Comment by blacksmoke26** [comment]
@plonknimbuzz Let's hope!

**Comment by alcaeus** [comment]
Hi! We are mainly offering basic support for this library because we have a direct need for it. However, we're not actively implementing features unless we need them. If any of you are willing to contribute such a feature, I'd be happy to help with the details.

**Comment by blacksmoke26** [comment]
@alcaeus Let us dig in throughly, Maybe there is something I can do!
