### ISSUE TITLE
Release New Version

### ISSUE THREAD

**Issue by dargmuesli** [thesoftwarefanatics/php-html-parser#16]
Would you please release a new version containing the most recent yet unpublished fixes? 8bda319ba0962752c97f4c7b9a04ecd612d999ca would make this project compatible with PHP 7.3.

**Comment by alcaeus** [comment]
I'll prepare a new release including PHP 7.3 compatibility over the next few days 👍

**Comment by dargmuesli** [comment]
Any updates? :)

**Comment by alcaeus** [comment]
[Merry Christmas](https://github.com/thesoftwarefanatics/php-html-parser/releases/tag/1.8.1)!

**Comment by dargmuesli** [comment]
Yay, wish you a relaxed time! :)
