### ISSUE TITLE
AbstractNode.php, wrapper for Tag.php setAttributes

### ISSUE THREAD

**Issue by IamSAB** [thesoftwarefanatics/php-html-parser#22]
Can't do
```php
$div = $form->find('div');
$div->setAttributes([
   'id' => 'main'
   'class' => 'block'
]);
```
as wrapper for this function is missing.

Also the `AbstractNode` class has a `$attr` property which I think is not necessary as attributes are stored in `Tag` class.

**Comment by alcaeus** [comment]
We will not be maintaining this library anymore. Since @paquettg has picked up work on the original library again, there is no need for us to maintain a separate version.
