### ISSUE TITLE
[Proposal] Fork paquettg/string-encode and fix iconv notices

### ISSUE THREAD

**Issue by blaaat** [thesoftwarefanatics/php-html-parser#8]
I assume paquettg/string-encode is unmaintained as well. 
Can we / I fork this and switch dependencies?

Currently the iconv call generates a notice and then a Exception is generated as well. I would like to prevent the notice (by either suppressing or temporary replacing the error_handler?). 

Loading a page with an incorrect character set in a meta tag now generates notices.
Example code with notice: 

```
$dom = new Dom; 
$dom->load('http://www.sanderback.us/test-html-parser.html'); 
foreach ($dom->find('a') as $link) {
	$x = $link->href;
}

```

**Comment by alcaeus** [comment]
> I assume paquettg/string-encode is unmaintained as well.

I assume so. We haven't forked those packages (yet) because they cause no problem on PHP 7.2.

> Can we / I fork this and switch dependencies?

If you are willing to maintain them, feel free to clone them yourself and send a pull request. If you'd rather have them maintained here with the rest of the parser, please let me know. Thanks!

**Comment by Gummibeer** [comment]
I would like to have them in one place (here).
